POST http://localhost:3001/api/initiatives
Content-Type: application/json

{
    "initiative":"lolobalo",
    "general_info": {
        "name": true,
        "birthdate": true ,
        "email": true
    }
}